### ISSUE TITLE
How to render page title ?

### ISSUE THREAD

**Issue by kousar2334** [HansSchouten/PHPagebuilder-boilerplate#6]
I have used this code to render a page
```
 public function viewPage($pageId)
   {
   	$theme = new Theme(config('pagebuilder.theme'), config('pagebuilder.theme.active_theme'));
   	$page = (new PageRepository)->findWithId($pageId);
   	$pageRenderer = new PageRenderer($theme, $page);
   	$html = $pageRenderer->render();
   	return $html;
   }
```
But the page title did not render.
![Screenshot_2020-07-02_12-52-14](https://user-images.githubusercontent.com/23190775/86326028-e7344200-bc62-11ea-9a4f-59fc9df9eadb.png)
.
In the master layout , I have written the code for title 
` <title><?= e($page->get('title')) ?></title>`

**Comment by HansSchouten** [comment]
Are you sure your page has a title in the database?

**Comment by kousar2334** [comment]
Yes ,
![Screenshot_2020-07-03_13-59-10](https://user-images.githubusercontent.com/23190775/86446234-7e69ca00-bd35-11ea-86a9-37a10fcf7ae4.png)

**Comment by HansSchouten** [comment]
It is advised to not include your domain in the route, so use: `/admin/pages/1` instead. The problem you have might be because of the custom `viewPage` method. Since you are not using the boilerplate, but you are using the Laravel version. Can't you just create a route like:
```
Route::any('{uri}', [
    'uses' => 'Http\Controllers\YourController@uri',
    'as' => 'webpage',
])->where('uri', '.*');
```
(put this route as your last route in the `routes.php` file)

And then use this controller method:
```
/**
 * Show the website page that corresponds with the current URI.
 */
public function uri()
{
    $pageBuilder = app()->make('phpPageBuilder');
    $pageBuilder->handlePublicRequest();
}
```
